title: NIH Bioinformatics Organization Community Directory
description: A community-created list of Bioinformatics organizations at NIH
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
